
logging:
  level:
    root: INFO

server.port: 8080

management:
  endpoints:
    web:
      exposure:
        include: info,health,env,metrics
      base-path: /management
  endpoint:
    health:
      show-details: always
      cache:
        time-to-live: 10000ms
    info:
      cache:
        time-to-live: 30000ms
    
spring:
  jackson:
    deserialization:
      accept-single-value-as-array: true
    serialization:
      write-dates-as-timestamps: false
    generator:
      write-numbers-as-strings: false
    default-property-inclusion: NON_NULL
    date-format: yyyy-MM-dd'T'HH:mm:ssZ
    
  webflux:
    base-path: /api/v1

okta:
  oauth2:
    client-secret: ${OKTA_CLIENT_ID}
    client-id: ${OKTA_CLIENT_SECRET}
    issuer: ${OKTA_SERVER_URI}
    scopes:
    - demo:register
    - demo:monitor
    - openid

pagination:
  default-page: 0
  default-size: 20
  
strategy:
  id:
    bu: FR
    storeIdFormat: "000"
    storeIdMax: 100
    supplierIdFormat: "00000000"
    supplierIdMax: 99999999
    fiscalIdFormat: "00000000"
    fiscalIdMax: 999999
