
logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: info,health,env,metrics
      base-path: /management
  endpoint:
    health:
      show-details: always
    
spring:

  jackson:
    deserialization:
      accept-single-value-as-array: true
    serialization:
      write-dates-as-timestamps: false
    generator:
      write-numbers-as-strings: false
    default-property-inclusion: NON_NULL
    date-format: yyyy-MM-dd'T'HH:mm:ssZ
    
  webflux:
    base-path: /api/v1

pagination:
  default-page: 0
  default-size: 20
  
strategy:
  id:
    bu: FR
    storeIdFormat: "000"
    storeIdMax: 100
    supplierIdFormat: "00000000"
    supplierIdMax: 99999999
    fiscalIdFormat: "00000000"
    fiscalIdMax: 999999

---  
spring.profiles: docker

server.port: 7000

logging:
  level:
    root: INFO
    '[org.springframework.jdbc.core]': TRACE
    '[org.springframework.transaction]': TRACE
    '[org.springframework.data.r2dbc]': TRACE
    
spring:

  r2dbc:
    url: r2dbc:mysql://mysql-suppliers:3306/suppliersdb
    username: michael
    password: jordan

  liquibase:
    change-log: classpath:liquibase/create-tables.xml
    enabled: true
    default-schema: suppliersdb
    url: jdbc:mysql://mysql-suppliers:3306/suppliersdb
    user: michael
    password: jordan
